### ISSUE TITLE
ditto for spanish

### ISSUE THREAD

**Issue by CristhianBoujon** [megagonlabs/ditto#1]
How many changes are required in order to implement for spanish language?

**Comment by oi02lyl** [comment]
I think you can do so by supporting the multilingual models here: https://huggingface.co/transformers/pretrained_models.html. For example, you can replace all the “distilbert-baes-uncased” with “distilbert-base-multilingual-cased” and see if it works or not.

**Comment by CristhianBoujon** [comment]
I'm going to try it and comment the results. Thank you!

**Comment by tchugh** [comment]
@CristhianBoujon Were you able to try the multi-lingual model? Did you also need to make any changes to the input data format? I see that in the WDC dataset, strings are followed by @fr, @es, @es as language tags.
